db:
  password: calories876
  user: caloriesuser
auth:
  cookie:
    httpOnly: true
    secure: true
cors:
  allowedOrigins: "http://localhost:3000"
spring:
  application:
    name: stonks
  datasource:
    url: jdbc:postgresql://localhost:5432/calories
    username: ${db.user}
    password: ${db.password}
  jpa.properties.hibernate:
    jdbc.lob.non_contextual_creation: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
    # Hibernate ddl auto (create, create-drop, validate, update)
    ddl-auto: update
  flyway:
    url : jdbc:postgresql://localhost:5432/calories
    schemas : migration
    user : ${db.user}
    password : ${db.password}
  redis:
    host: localhost
    port: 6379
logging:
  level:
    root=: INFO