services:
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_DB=auth
      - POSTGRES_PASSWORD=auth876
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
